# This workflow performs linting and formatting checks based on
# our defined clang-format and clang-tidy configurations.

# The workflow is triggered on pull requests and checks for changes in C++ files.
# If changes are detected, the workflow installs grabs the latest
# Docker container, and runs linting/formatting tests.

# If the checks pass, the workflow will report success. If the checks fail,
# the workflow will report failure.

name: lint-format-test

on: [pull_request]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/coopeaus/nes-emulator/build-lint-container:latest

      - name: Run Linter
        run: |
          # Build and lint
          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            build

          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            lint

      - name: Run Nestest ROM
        run: |
          touch ./tests/output/my_nestest-log.txt
          chmod ugo+rw ./tests/output/my_nestest-log.txt

          # Test, using the build from before
          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            test "RomTests.Nestest"
