# This workflow performs linting and formatting checks based on
# our defined clang-format and clang-tidy configurations.

# The workflow is triggered on pull requests and checks for changes in C++ files.
# If changes are detected, the workflow installs grabs the latest
# Docker container, and runs linting/formatting tests. 

# If the checks pass, the workflow will report success. If the checks fail,
# the workflow will report failure.

name: lint-format-test

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in C++ files
        id: check_changes
        run: |
          git fetch origin main
          if git diff --name-only origin/main ${{ github.sha }} | grep -E '\.(cpp|hpp|c|h)$' -q; then
            echo "files_modified=true" >> $GITHUB_ENV
          else
            echo "files_modified=false" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        if: env.files_modified == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        if: env.files_modified == 'true'
        run: |
          docker pull ghcr.io/coopeaus/nes-emulator/build-lint-container:latest

      - name: Run Linter
        if: env.files_modified == 'true'
        run: |
          docker run -e CI=${CI} -v $(pwd):/workspace -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest lint
      
      - name: Run Nestest ROM
        if: env.files_modified == 'true'
        run: |
          docker run -e CI=${CI} -v $(pwd):/workspace -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest build && \
          docker run -e CI=${CI} -v $(pwd):/workspace -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest test "RomTests.Nestest"
